import { generateQueryParams } from '@/app/search/form/helpers/generate-query-parameter';

describe('generateQueryParams', () => {
  test('should generate the correct query parameters based on the provided state', () => {
    const state = {
      selectedShape: 'round',
      selectedWhiteColor: 'D',
      selectedFancyColor: 'blue',
      selectedIntensity: 'strong',
      selectedOvertone: 'pink',
      selectedTinge: 'brown',
      selectedTingeIntensity: 'medium',
      selectedClarity: 'VS1',
      selectedCaratRange: ['0.5-1', '1-1.5'],
      selectedCut: 'excellent',
      selectedPolish: 'excellent',
      selectedSymmetry: 'very_good',
      selectedFluorescence: 'strong_blue',
      selectedCulet: 'none',
      selectedGirdle: 'thin_to_medium',
      selectedKeyToSymbol: 'GIA',
      selectedLab: 'IGI',
      selectedHR: 'yes',
      selectedBrilliance: 'excellent',
      selectedLocation: 'New York',
      selectedOrigin: 'USA',
      priceRangeFrom: 2000,
      priceRangeTo: 5000,
      discountFrom: 5,
      discountTo: 15,
      pricePerCaratFrom: 1000,
      pricePerCaratTo: 3000,
      blackTableBI: 'none',
      sideBlackBI: 'none',
      openCrownBI: 'none',
      openTableBI: 'none',
      openPavilionBI: 'none',
      milkyBI: 'none',
      lusterBI: 'excellent',
      eyeCleanBI: 'yes',
      tableInclusionWI: 'none',
      sideInclusionWI: 'none',
      naturalCrownWI: 'none',
      naturalGirdleWI: 'none',
      naturalPavilionWI: 'none',
      surfaceGrainingWI: 'none',
      internalGrainingWI: 'none',
      tablePerFrom: 55,
      tablePerTo: 60,
      depthFrom: 60,
      depthTo: 65,
      crownAngleFrom: 30,
      crownAngleTo: 35,
      lengthFrom: 4.8,
      lengthTo: 5.2,
      pavilionDepthFrom: 40,
      pavilionDepthTo: 45,
      depthPerFrom: 58,
      depthPerTo: 62,
      crownHeightFrom: 10,
      crownHeightTo: 15,
      widthFrom: 4.8,
      widthTo: 5.2,
      lowerHalfFrom: 75,
      lowerHalfTo: 80,
      ratioFrom: 1,
      ratioTo: 1.2,
      girdlePerFrom: 1,
      girdlePerTo: 2,
      pavilionAngleFrom: 40,
      pavilionAngleTo: 45,
      starLengthFrom: 40,
      starLengthTo: 45
    };

    const result = generateQueryParams(state);

    expect(result).toEqual({
      shape: 'round',
      color: 'D',
      fancy: 'blue',
      intensity: 'strong',
      overtone: 'pink',
      color_shade: 'brown',
      color_shade_intensity: 'medium',
      clarity: 'VS1',
      carat: [
        { lte: 1, gte: 0.5 },
        { lte: 1.5, gte: 1 }
      ],
      cut: 'excellent',
      polish: 'excellent',
      symmetry: 'very_good',
      fluorescence: 'strong_blue',
      culet: 'none',
      girdle: 'thin_to_medium',
      key_to_symbol: 'GIA',
      lab: 'IGI',
      ha: 'yes',
      brilliance: 'excellent',
      location: 'New York',
      origin_country: 'USA',
      price_range: { lte: 5000, gte: 2000 },
      discount: { lte: 15, gte: 5 },
      price_per_carat: { lte: 3000, gte: 1000 },
      black_table: 'none',
      side_black: 'none',
      open_crown: 'none',
      open_table: 'none',
      open_pavilion: 'none',
      milky: 'none',
      luster: 'excellent',
      eye_clean: 'yes',
      table_inclusion: 'none',
      side_inclusion: 'none',
      natural_crown: 'none',
      natural_girdle: 'none',
      natural_pavilion: 'none',
      surface_graining: 'none',
      internal_graining: 'none',
      table_percentage: { lte: 60, gte: 55 },
      depth: { lte: 65, gte: 60 },
      crown_angle: { lte: 35, gte: 30 },
      length: { lte: 5.2, gte: 4.8 },
      pavilion_depth: { lte: 45, gte: 40 },
      depth_percentage: { lte: 62, gte: 58 },
      crown_height: { lte: 15, gte: 10 },
      width: { lte: 5.2, gte: 4.8 },
      lower_half: { lte: 80, gte: 75 },
      ratio: { lte: 1.2, gte: 1 },
      girdle_percentage: { lte: 2, gte: 1 },
      pavilion_angle: { lte: 45, gte: 40 },
      star_length: { lte: 45, gte: 40 }
    });
  });
});
