export const Tracking = {
  Click_RegisterPage: 'Click_RegisterPage',
  Register_PageView: 'Register_PageView',
  Click_Register: 'Click_Register',
  Click_Login: 'Click_Login',
  Click_Back_Register_Page: 'Click_Back_Register_Page',
  Click_KGK_Logo: 'Click_KGK_Logo',
  OTP_Sent: 'OTP_Sent',
  Mobile_Verification_PageView: 'Mobile_Verification_PageView',
  Click_Back_Mobile_Verification_Page: 'Click_Back_Mobile_Verification_Page',
  Click_Verify: 'Click_Verify',
  Click_Resend: 'Click_Resend',
  OTP_Resend: 'OTP_Resend',
  Click_Mobile_Edit: 'Click_Mobile_Edit',
  Click_Mobile_Edit_Save: 'Click_Mobile_Edit_Save',
  OTP_Sent_New: 'OTP_Sent_New',
  Click_Mobile_Edit_Cancel: 'Click_Mobile_Edit_Cancel',
  Mobile_Verified_PageView: 'Mobile_Verified_PageView',
  Click_Back_Mobile_Verified_Page: 'Click_Back_Mobile_Verified_Page',
  Click_Finish_KYC: 'Click_Finish_KYC',
  Click_Continue_Guest: 'Click_Continue_Guest'
};

export const Tracking_Click_RegisterPage = {
  LP_Top_Register: 'LP_Top_Register',
  LP_Top_Login: 'LP_Top_Login',
  LP_Home_Explore_Now_Register: 'LP_Home_Explore_Now_Register',
  LP_Home_Bottom_Register: 'LP_Home_Bottom_Register',
  LP_Leadership_Bottom_Register: 'LP_Leadership_Bottom_Register',
  LP_OurStory_Bottom_Register: 'LP_OurStory_Bottom_Register',
  LP_Sustainability_Bottom_Register: 'LP_Sustainability_Bottom_Register',
  LP_Traceability_Bottom_Register: 'LP_Traceability_Bottom_Register',
  LP_ContactUs_Bottom_Register: 'LP_ContactUs_Bottom_Register',
  Login_Register: 'Login_Register',
  LP_Blogs_Bottom_Register: 'LP_Blogs_Bottom_Register',
  LP_GemTrac_Bottom_Register: 'LP_GemTrac_Bottom_Register'
};

export const Tracking_KYC = {
  Click_KYC: 'Click_KYC',
  KYC_Country_PageView: 'KYC_Country_PageView',
  KYC_Country_India: 'KYC_Country_India',
  KYC_Country_Dubai: 'KYC_Country_Dubai',
  KYC_Country_Belgium: 'KYC_Country_Belgium',
  KYC_Country_US: 'KYC_Country_US',
  KYC_Form_PageView: 'KYC_Form_PageView',
  KYC_Form_Online_Form_Selection: 'KYC_Form_Online_Form_Selection',
  KYC_Form_Offline_Form_Selection: 'KYC_Form_Offline_Form_Selection',
  Click_Back_KYC_Form: 'Click_Back_KYC_Form',
  Click_Back_KYC_Personal_Details: 'Click_Back_KYC_Personal_Details',
  KYC_Form_Personal_Details_PageView: 'KYC_Form_Personal_Details_PageView',
  Click_Verify_Email: 'Click_Verify_Email',
  Email_OTP_Sent: 'Email_OTP_Sent',
  KYC_Email_Verification_PageView: 'KYC_Email_Verification_PageView',
  KYC_Email_Verification_Resend_OTP: 'KYC_Email_Verification_Resend_OTP',
  KYC_Email_Verification_Click_Verify: 'KYC_Email_Verification_Click_Verify',
  Email_OTP_Resent: 'Email_OTP_Resent',
  Click_Next_KYC_Personal_Details: 'Click_Next_KYC_Personal_Details',
  KYC_Company_Details_PageView: 'KYC_Company_Details_PageView',
  Click_Next_KYC_Company_Details: 'Click_Next_KYC_Company_Details',
  Click_Back_KYC_Company_Details: 'Click_Back_KYC_Company_Details',
  KYC_Owner_Details_PageView: 'KYC_Owner_Details_PageView',
  Click_Next_KYC_Owner_Details: 'Click_Next_KYC_Owner_Details',
  Click_Back_KYC_Owner_Details: 'Click_Back_KYC_Owner_Details',
  KYC_Banking_Details_PageView: 'KYC_Banking_Details_PageView',
  Click_Next_KYC_Banking_Details: 'Click_Next_KYC_Banking_Details',
  Click_Back_KYC_Banking_Details: 'Click_Back_KYC_Banking_Details',
  KYC_Attachment_PageView: 'KYC_Attachment_PageView',
  Click_Submit_KYC_Attachment: 'Click_Submit_KYC_Attachment',
  Click_Back_KYC_Attachment: 'Click_Back_KYC_Attachment',
  KYC_Status_Pending_Pageview: 'KYC_Status_Pending_Pageview',
  KYC_Offline_Form_Pageview: 'KYC_Offline_Form_Pageview',
  KYC_Offline_Form_Submit: 'KYC_Offline_Form_Submit',
  KYC_Offline_Form_Back: 'KYC_Offline_Form_Back'
};

export const Tracking_Search_By_Text = {
  search_by_text_initiated: 'search_by_text_initiated',
  search_by_text_executed: 'search_by_text_executed',
  results_page_pageview: 'results_page_pageview',
  click_back_results_page: 'click_back_results_page',
  click_stone_dna_page: 'click_stone_dna_page',
  dna_page_pageview: 'dna_page_pageview',
  click_stone_image_arrow_dna_page: 'click_stone_image_arrow_dna_page',
  click_stone_b2b_dna_page: 'click_stone_b2b_dna_page',
  click_stone_sparkle_dna_page: 'click_stone_sparkle_dna_page',
  click_stone_certificate_dna_page: 'click_stone_certificate_dna_page',
  click_back_dna_page: 'click_back_dna_page',
  click_confirm_stone_dna_page: 'click_confirm_stone_dna_page',
  click_add_to_cart_dna_page: 'click_add_to_cart_dna_page',
  click_download_excel_dna_page: 'click_download_excel_dna_page',
  click_share_dna_page: 'click_share_dna_page',
  click_media_link_dna_page: 'click_media_link_dna_page',
  click_stone_lab_result_page: 'click_stone_lab_result_page',
  click_stone_assets_result_page: 'click_stone_assets_result_page',
  click_stone_image_arrow_result_page: 'click_stone_image_arrow_result_page',
  click_stone_b2b_result_page: 'click_stone_b2b_result_page',
  click_stone_sparkle_result_page: 'click_stone_sparkle_result_page',
  click_stone_certificate_result_page: 'click_stone_certificate_result_page',
  click_download_excel_result_page: 'click_download_excel_result_page',
  click_share_result_page: 'click_share_result_page',
  click_add_to_cart_result_page: 'click_add_to_cart_result_page',
  click_confirm_stone_result_page: 'click_confirm_stone_result_page',
  click_compare_stone_result_page: 'click_compare_stone_result_page',
  click_book_appointment_result_page: 'click_book_appointment_result_page',
  confirm_page_pageview: 'confirm_page_pageview',
  click_back_confirm_page: 'click_back_confirm_page',
  click_add_comment_confirm_page: 'click_add_comment_confirm_page',
  click_confirm_stone_confirm_page: 'click_confirm_stone_confirm_page',
  disclaimer_pop_up_opens: 'disclaimer_pop_up_opens',
  click_confirm_order_disclaimer_pop_up:
    'click_confirm_order_disclaimer_pop_up',
  order_executed_pop_up: 'order_executed_pop_up',
  click_go_to_your_order_order_executed_pop_up:
    'click_go_to_your_order_order_executed_pop_up',
  click_continue_order_executed_pop_up: 'click_continue_order_executed_pop_up'
};

export const Tracking_KYC_Entry_Point = {
  KYC_Bottom_Sheet: 'KYC_Bottom_Sheet',
  KYC_Top_Button: 'KYC_Top_Button',
  KYC_Registration_Page: 'KYC_Registration_Page'
};

export const Tracking_Dashboard = {
  page_view: 'page_view',
  click_search_by_text: 'click_search_by_text',
  click_enter_search_by_text: 'click_enter_search_by_text',
  click_search: 'click_search',
  click_match_pair_search: 'click_match_pair_search',
  click_new_arrivals: 'click_new_arrivals',
  click_bid_to_buy: 'click_bid_to_buy',
  click_individual_saved_search: 'click_individual_saved_search',
  click_saved_search: 'click_saved_search',
  click_individual_order: 'click_individual_order',
  click_your_orders: 'click_your_orders',
  click_on_carousel: 'click_on_carousel',
  click_on_my_cart: 'click_on_my_cart',
  click_kam_card: 'click_kam_card',
  click_terms_and_conditions: 'click_terms_and_conditions',
  click_privacy_policy: 'click_privacy_policy',
  click_my_appointments: 'click_my_appointments',
  click_faqs: 'click_faqs',
  click_support_icon: 'click_support_icon',
  click_notifications: 'click_notifications',
  click_top_right_navigation: 'click_top_right_navigation',
  click_on_my_account: 'click_on_my_account',
  click_on_logout: 'click_on_logout',
  click_kgk_logo: 'click_kgk_logo',
  click_bid_to_buy_dropdown: 'click_bid_to_buy_dropdown',
  click_notify_sales: 'click_notify_sales',
  click_complete_kyc: 'click_complete_kyc'
};

export const Tracking_Dashboard_Destination_Page = {
  search_form_results: 'search_form_results',
  new_arrivals: 'new_arrivals',
  bid_to_buy: 'bid_to_buy',
  search_form: 'search_form',
  match_pair_form: 'match_pair_form',
  match_pair_results: 'match_pair_results',
  saved_search: 'saved_search',
  individual_order: 'individual_order',
  your_orders: 'your_orders',
  my_cart: 'my_cart',
  terms_and_conditions: 'terms_and_conditions',
  privacy_policy: 'privacy_policy',
  my_appointment_form: 'my_appointment_form',
  my_appointments: 'my_appointments',
  faqs: 'faqs',
  my_account: 'my_account',
  login: 'login',
  kyc: 'kyc'
};
