export const handleReset = (
  setState: any,
  errorSetState: any
  // setValidationError: any
) => {
  const {
    setSelectedShape,
    setSelectedWhiteColor,
    setSelectedFancyColor,
    setSelectedIntensity,
    setSelectedOvertone,
    setSelectedShade,
    setSelectedClarity,
    setSelectedGirdleStep,
    setSelectedCaratRange,
    setSelectedMake,
    setSelectedCut,
    setSelectedPolish,
    setSelectedSymmetry,
    setSelectedFluorescence,
    setSelectedCulet,
    setSelectedKeyToSymbol,
    setSelectedLab,
    setSelectedLocation,
    setSelectedOrigin,
    setAmountRangeMin,
    setAmountRangeMax,
    setDiscountMin,
    setDiscountMax,
    setCaratMin,
    setCaratMax,
    setPricePerCaratMin,
    setPricePerCaratMax,
    setCaratRangeFrom,
    setCaratRangeTo,
    setBlackTable,
    setSideBlack,
    setOpenCrown,
    setOpenTable,
    setOpenPavilion,
    setMilky,
    setLuster,
    setEyeClean,
    setTableInclusion,
    setSideInclusion,
    setNaturalCrown,
    setNaturalGirdle,
    setNaturalPavilion,
    setSurfaceGraining,
    setInternalGraining,
    setTablePerMin,
    setTablePerMax,
    setDepthMin,
    setDepthMax,
    setCrownAngleMax,
    setCrownAngleMin,
    setLengthMax,
    setLengthMin,
    setPavilionHeightMax,
    setPavilionHeightMin,
    setDepthPerMax,
    setDepthPerMin,
    setCrownHeightMax,
    setCrownHeightMin,
    setWidthMax,
    setWidthMin,
    setLowerHalfMax,
    setLowerHalfMin,
    setRatioMax,
    setRatioMin,
    setGirdlePerMax,
    setGirdlePerMin,
    setPavilionAngleMax,
    setPavilionAngleMin,
    setStarLengthMax,
    setStarLengthMin,
    // setSelectedColor,
    setSelectedGirdle
  } = setState;

  const {
    setTablePerError,
    setDepthPerError,
    setRatioError,
    setLengthError,
    setWidthError,
    setDepthError,
    setCrownAngleError,
    setCrownHeightError,
    setGirdlePerError,
    setPavilionAngleError,
    setPavilionHeightError,
    setLowerHalfError,
    setStarLengthError,
    setGirdleError,
    setCaratError,
    setDiscountError,
    setPricePerCaratError,
    setAmountRangeError
  } = errorSetState;

  setSelectedShape([]);
  setSelectedWhiteColor([]);
  // setSelectedColor('');
  setSelectedFancyColor('');
  setSelectedIntensity('');
  setSelectedOvertone('');
  setSelectedShade([]);
  setSelectedClarity([]);
  setSelectedCaratRange([]);
  setSelectedMake('');
  setSelectedCut([]);
  setSelectedPolish([]);
  setSelectedSymmetry([]);
  setSelectedFluorescence([]);
  setSelectedLab([]);
  setAmountRangeMin('');
  setAmountRangeMax('');
  setDiscountMin('');
  setDiscountMax('');
  setCaratMin('');
  setCaratMax('');
  setPricePerCaratMin('');
  setPricePerCaratMax('');
  setCaratRangeFrom('');
  setCaratRangeTo('');
  setTablePerMin('');
  setTablePerMax('');
  setDepthMin('');
  setDepthMax('');
  setCrownAngleMax('');
  setCrownAngleMin('');
  setLengthMax('');
  setLengthMin('');
  setPavilionHeightMax('');
  setPavilionHeightMin('');
  setDepthPerMax('');
  setDepthPerMin('');
  setCrownHeightMax('');
  setCrownHeightMin('');
  setWidthMax('');
  setWidthMin('');
  setLowerHalfMax('');
  setLowerHalfMin('');
  setRatioMax('');
  setRatioMin('');
  setGirdlePerMax('');
  setGirdlePerMin('');
  setPavilionAngleMax('');
  setPavilionAngleMin('');
  setStarLengthMax('');
  setStarLengthMin('');
  setBlackTable([]);
  setSideBlack([]);
  setOpenCrown([]);
  setOpenTable([]);
  setOpenPavilion([]);
  setMilky([]);
  setLuster([]);
  setEyeClean([]);
  setTableInclusion([]);
  setSideInclusion([]);
  setNaturalCrown([]);
  setNaturalGirdle([]);
  setNaturalPavilion([]);
  setSurfaceGraining([]);
  setInternalGraining([]);
  setSelectedLocation([]);
  setSelectedOrigin([]);
  setSelectedCulet([]);
  setSelectedKeyToSymbol([]);
  setSelectedGirdleStep('');
  setSelectedGirdle([]);

  //Empty Error States
  setTablePerError('');
  setDepthPerError('');
  setRatioError('');
  setLengthError('');
  setWidthError('');
  setDepthError('');
  setCrownAngleError('');
  setCrownHeightError('');
  setGirdlePerError('');
  setPavilionAngleError('');
  setPavilionHeightError('');
  setLowerHalfError('');
  setStarLengthError('');
  setGirdleError('');
  setCaratError('');
  setDiscountError('');
  setPricePerCaratError('');
  setAmountRangeError('');
  // setValidationError('');
};
