import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/_globals.scss";
// import store from "@/hooks/store";
import { Providers } from "./Providers";
import SideBar from "@/components/common/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KGK 2.O",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider store={store}> */}

        <Providers>{children}</Providers>
        {/* </Provider> */}
      </body>
    </html>
  );
}
