import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../styles/_globals.scss';
// import store from "@/hooks/store";
import { Providers } from './Providers';
import { TopNavigationBar } from '@/components/common/top-navigation-bar';
import { BottomNavigationBar } from '@/components/common/bottom-navigation-bar';
import SideBar from '@/components/common/sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'KGK 2.O',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <SideBar />
          <TopNavigationBar />
          <div
            style={{
              display: 'flex',
              justifyContent: 'right',
              marginTop: '110px',
              padding: '0px 30px',
            }}
          >
            <main style={{ width: 'calc(100% - 92px)', minHeight: '76vh' }}>
              {children}
            </main>
          </div>
          <BottomNavigationBar />
        </Providers>
      </body>
    </html>
  );
}
