import { IKeyLabelMapping } from '../interface';

// Define key-label mapping for stone properties
export const keyLabelMapping: IKeyLabelMapping = {
  id: 'id',
  shape: 'Shape',
  lab: 'Lab',
  rap: 'Rap($)',
  price_per_carat: 'PR/CT',
  carat: 'Carat',
  color: 'Color',
  clarity: 'Clarity',
  color_shade: 'Color Shade',
  cut: 'Cut',
  polish: 'Polish',
  crown_angle: 'C/A',
  crown_height: 'C/H',
  symmetry: 'Symmetry',
  table_percentage: 'Table%',
  depth_percentage: 'Depth%',
  width: 'Width',
  depth: 'Depth',
  ratio: 'Ratio',
  ha: 'H&A',
  girdle: 'Girdle',
  pavilion_angle: 'P/A',
  pavilion_depth: 'P/D',
  culet: 'Culet',
  inscription: 'Ins.',
  origin_country: 'Origin',
  star_length: 'S/L',
  girdle_percentage: 'Girdle%',
  luster: 'Luster',
};
