export const handleReset = (setState: any, errorSetState: any) => {
  const {
    setSelectedShape,
    setSelectedColor,
    setSelectedFancyColor,
    setSelectedIntensity,
    setSelectedOvertone,
    setSelectedTinge,
    setSelectedClarity,
    setSelectedGirdleStep,
    setSelectedCaratRange,
    setSelectedMake,
    setSelectedCut,
    setSelectedPolish,
    setSelectedSymmetry,
    setSelectedFluorescence,
    setSelectedCulet,
    setSelectedKeyToSymbol,
    setSelectedLab,
    setSelectedLocation,
    setSelectedOrigin,
    setPriceRangeFrom,
    setPriceRangeTo,
    setDiscountFrom,
    setDiscountTo,
    setPricePerCaratFrom,
    setPricePerCaratTo,
    setCaratRangeFrom,
    setCaratRangeTo,
    setBlackTableBI,
    setSideBlackBI,
    setOpenCrownBI,
    setOpenTableBI,
    setOpenPavilionBI,
    setMilkyBI,
    setLusterBI,
    setEyeCleanBI,
    setTableInclusionWI,
    setSideInclusionWI,
    setNaturalCrownWI,
    setNaturalGirdleWI,
    setNaturalPavilionWI,
    setSurfaceGrainingWI,
    setInternalGrainingWI,
    setTablePerFrom,
    setTablePerTo,
    setCrownAngleFrom,
    setCrownAngleTo,
    setLengthFrom,
    setLengthTo,
    setPavilionDepthFrom,
    setPavilionDepthTo,
    setDepthPerFrom,
    setDepthPerTo,
    setCrownHeightFrom,
    setCrownHeightTo,
    setWidthFrom,
    setWidthTo,
    setLowerHalfFrom,
    setLowerHalfTo,
    setRatioFrom,
    setRatioTo,
    setGirdlePerFrom,
    setGirdlePerTo,
    setPavilionAngleFrom,
    setPavilionAngleTo,
    setStarLengthFrom,
    setStarLengthTo,
    setGirdleFrom,
    setGirdleTo
  } = setState;

  const {
    setTablePerError,
    setDepthPerError,
    setRatioError,
    setLengthError,
    setWidthError,
    setDepthError,
    setCrownAngleError,
    setCrownHeightError,
    setGirdlePerError,
    setPavilionAngleError,
    setPavilionHeightError,
    setLowerHalfError,
    setStarLengthError,
    setGirdleError,
    setCaratError,
    setDiscountError,
    setPricePerCaratError,
    setAmountRangeError
  } = errorSetState;

  setSelectedShape([]);
  setSelectedColor('');
  setSelectedFancyColor([]);
  setSelectedIntensity([]);
  setSelectedOvertone([]);
  setSelectedTinge([]);
  setSelectedClarity([]);
  setSelectedCaratRange([]);
  setSelectedMake('');
  setSelectedCut([]);
  setSelectedPolish([]);
  setSelectedSymmetry([]);
  setSelectedFluorescence([]);
  setSelectedLab([]);
  setPriceRangeFrom('');
  setPriceRangeTo('');
  setDiscountFrom('');
  setDiscountTo('');
  setPricePerCaratFrom('');
  setPricePerCaratTo('');
  setCaratRangeFrom('');
  setCaratRangeTo('');
  setBlackTableBI([]);
  setSideBlackBI([]);
  setOpenCrownBI([]);
  setOpenTableBI([]);
  setOpenPavilionBI([]);
  setMilkyBI([]);
  setLusterBI([]);
  setEyeCleanBI([]);
  setTableInclusionWI([]);
  setSideInclusionWI([]);
  setNaturalCrownWI([]);
  setNaturalGirdleWI([]);
  setNaturalPavilionWI([]);
  setSurfaceGrainingWI([]);
  setInternalGrainingWI([]);
  setTablePerFrom('');
  setTablePerTo('');
  setCrownAngleFrom('');
  setCrownAngleTo('');
  setLengthFrom('');
  setLengthTo('');
  setPavilionDepthFrom('');
  setPavilionDepthTo('');
  setDepthPerFrom('');
  setDepthPerTo('');
  setCrownHeightFrom('');
  setCrownHeightTo('');
  setWidthFrom('');
  setWidthTo('');
  setLowerHalfFrom('');
  setLowerHalfTo('');
  setRatioFrom('');
  setRatioTo('');
  setGirdlePerFrom('');
  setGirdlePerTo('');
  setPavilionAngleFrom('');
  setPavilionAngleTo('');
  setStarLengthFrom('');
  setStarLengthTo('');
  setSelectedLocation([]);
  setSelectedOrigin([]);
  setSelectedCulet([]);
  setGirdleFrom('');
  setGirdleTo('');
  setSelectedKeyToSymbol([]);
  setSelectedGirdleStep('');

  //Empty Error States
  setTablePerError('');
  setDepthPerError('');
  setRatioError('');
  setLengthError('');
  setWidthError('');
  setDepthError('');
  setCrownAngleError('');
  setCrownHeightError('');
  setGirdlePerError('');
  setPavilionAngleError('');
  setPavilionHeightError('');
  setLowerHalfError('');
  setStarLengthError('');
  setGirdleError('');
  setCaratError('');
  setDiscountError('');
  setPricePerCaratError('');
  setAmountRangeError('');
};
