import fieldStateManagement from './field-state-management';

const { setState } = fieldStateManagement();

const {
  setSelectedShape,
  setSelectedColor,
  setSelectedWhiteColor,
  setSelectedFancyColor,
  setSelectedIntensity,
  setSelectedOvertone,
  setSelectedTinge,
  setSelectedTingeIntensity,
  setSelectedClarity,
  setSelectedGirdleStep,
  setSelectedCaratRange,
  setSelectedMake,
  setSelectedCut,
  setSelectedPolish,
  setSelectedSymmetry,
  setSelectedFluorescence,
  setSelectedCulet,
  setSelectedGirdle,
  setSelectedKeyToSymbol,
  setSelectedLab,
  setSelectedHR,
  setSelectedBrilliance,
  setSelectedLocation,
  setSelectedOrigin,
  setPriceRangeFrom,
  setPriceRangeTo,
  setDiscountFrom,
  setDiscountTo,
  setPricePerCaratFrom,
  setPricePerCaratTo,
  setCaratRangeFrom,
  setCaratRangeTo,
  setBlackTableBI,
  setSideBlackBI,
  setOpenCrownBI,
  setOpenTableBI,
  setOpenPavilionBI,
  setMilkyBI,
  setLusterBI,
  setEyeCleanBI,
  setTableInclusionWI,
  setSideInclusionWI,
  setNaturalCrownWI,
  setNaturalGirdleWI,
  setNaturalPavilionWI,
  setSurfaceGrainingWI,
  setInternalGrainingWI,
  setTablePerFrom,
  setTablePerTo,
  setCrownAngleFrom,
  setCrownAngleTo,
  setLengthFrom,
  setLengthTo,
  setPavilionDepthFrom,
  setPavilionDepthTo,
  setDepthPerFrom,
  setDepthPerTo,
  setCrownHeightFrom,
  setCrownHeightTo,
  setWidthFrom,
  setWidthTo,
  setLowerHalfFrom,
  setLowerHalfTo,
  setRatioFrom,
  setRatioTo,
  setGirdlePerFrom,
  setGirdlePerTo,
  setPavilionAngleFrom,
  setPavilionAngleTo,
  setStarLengthFrom,
  setStarLengthTo,
} = setState;
export const handleReset = () => {
  setSelectedShape([]);
  setSelectedColor('');
  setSelectedWhiteColor([]);
  setSelectedFancyColor([]);
  setSelectedIntensity([]);
  setSelectedOvertone([]);
  setSelectedTinge([]);
  setSelectedTingeIntensity([]);
  setSelectedClarity([]);
  setSelectedCaratRange([]);
  setSelectedMake('');
  setSelectedCut([]);
  setSelectedPolish([]);
  setSelectedSymmetry([]);
  setSelectedFluorescence([]);
  setSelectedLab([]);
  setSelectedHR([]);
  setSelectedBrilliance([]);
  setPriceRangeFrom('');
  setPriceRangeTo('');
  setDiscountFrom('');
  setDiscountTo('');
  setPricePerCaratFrom('');
  setPricePerCaratTo('');
  setCaratRangeFrom('');
  setCaratRangeTo('');
  setBlackTableBI([]);
  setSideBlackBI([]);
  setOpenCrownBI([]);
  setOpenTableBI([]);
  setOpenPavilionBI([]);
  setMilkyBI([]);
  setLusterBI([]);
  setEyeCleanBI([]);
  setTableInclusionWI([]);
  setSideInclusionWI([]);
  setNaturalCrownWI([]);
  setNaturalGirdleWI([]);
  setNaturalPavilionWI([]);
  setSurfaceGrainingWI([]);
  setInternalGrainingWI([]);
  setTablePerFrom('');
  setTablePerTo('');
  setCrownAngleFrom('');
  setCrownAngleTo('');
  setLengthFrom('');
  setLengthTo('');
  setPavilionDepthFrom('');
  setPavilionDepthTo('');
  setDepthPerFrom('');
  setDepthPerTo('');
  setCrownHeightFrom('');
  setCrownHeightTo('');
  setWidthFrom('');
  setWidthTo('');
  setLowerHalfFrom('');
  setLowerHalfTo('');
  setRatioFrom('');
  setRatioTo('');
  setGirdlePerFrom('');
  setGirdlePerTo('');
  setPavilionAngleFrom('');
  setPavilionAngleTo('');
  setStarLengthFrom('');
  setStarLengthTo('');
  setSelectedLocation([]);
  setSelectedOrigin([]);
  setSelectedCulet([]);
  setSelectedGirdle([]);
  setSelectedKeyToSymbol([]);
  setSelectedGirdleStep('');
};
